.Dd June 5, 2020
.Dt ALIGN 1
.Os
.Sh NAME
.Nm align
.Nd center or right-align a text file
.Sh SYNOPSIS
.Nm
.Fl C|c|R|r
.Op Fl w Ar width
.Sh DESCRIPTION
Copies a file from standard input to standard output,
indented with spaces to be centered or right-align, depending on
the chosen mode:
.Pp
.Bl -tag -width Ds -compact
.It Fl C
Center as a block
.It Fl c
Center per line
.It Fl R
Right-align as a block
.It Fl r
Right-align per line
.El
.Pp
Tabs are expanded.
The target width can be set with
.Fl w Ar width
and defaults to the
.Ev COLUMNS
environment variable, or 80 if unset.
.Sh EXAMPLES
Centering a file block and per-line modes respectively:
.Bd -literal -offset indent
$ align -C <poem.txt

       Into the machine
       The soul descended
       Speaking to its creator
       Greeting the world

$ align -c <poem.txt

          Into the machine
         The soul descended
       Speaking to its creator
         Greeting the world
.Ed
.Sh AUTHORS
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl
